// <auto-generated />
using System;
using Cotton.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cotton.Server.Migrations
{
    [DbContext(typeof(CottonDbContext))]
    [Migration("20251014044935_AddSizes")]
    partial class AddSizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cotton.Server.Database.Models.Chunk", b =>
                {
                    b.Property<byte[]>("Sha256")
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.HasKey("Sha256");

                    b.ToTable("chunks");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.ChunkOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ChunkSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chunk_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("chunk_ownerships");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FileManifestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FileManifestId");

                    b.HasIndex("OwnerId", "Folder");

                    b.HasIndex("OwnerId", "Folder", "Name")
                        .IsUnique();

                    b.ToTable("file_manifests");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifestChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_order");

                    b.Property<byte[]>("ChunkSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chunk_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChunkSha256");

                    b.HasIndex("FileManifestId", "ChunkOrder")
                        .IsUnique();

                    b.ToTable("file_manifest_chunks");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.ChunkOwnership", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifest", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.FileManifest", null)
                        .WithMany("FileManifests")
                        .HasForeignKey("FileManifestId");

                    b.HasOne("Cotton.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifestChunk", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.Chunk", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkSha256")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Server.Database.Models.FileManifest", "FileManifest")
                        .WithMany()
                        .HasForeignKey("FileManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("FileManifest");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifest", b =>
                {
                    b.Navigation("FileManifests");
                });
#pragma warning restore 612, 618
        }
    }
}
