// <auto-generated />
using System;
using Cotton.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cotton.Server.Migrations
{
    [DbContext(typeof(CottonDbContext))]
    [Migration("20251025054012_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cotton.Server.Database.Models.Chunk", b =>
                {
                    b.Property<byte[]>("Sha256")
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Sha256");

                    b.ToTable("chunks");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.ChunkOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ChunkSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chunk_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "ChunkSha256")
                        .IsUnique();

                    b.ToTable("chunk_ownerships");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FileManifestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VersionStableId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_stable_id");

                    b.HasKey("Id");

                    b.HasIndex("FileManifestId");

                    b.HasIndex("OwnerId");

                    b.ToTable("file_manifests");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifestChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_order");

                    b.Property<byte[]>("ChunkSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chunk_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChunkSha256");

                    b.HasIndex("FileManifestId", "ChunkOrder")
                        .IsUnique();

                    b.ToTable("file_manifest_chunks");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("layouts");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.HasIndex("LayoutId", "Name", "ParentId", "Type")
                        .IsUnique();

                    b.ToTable("nodes");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.NodeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_manifest_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("FileManifestId", "NodeId")
                        .IsUnique();

                    b.ToTable("node_files");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordPhc")
                        .HasColumnType("text")
                        .HasColumnName("password_phc");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.ChunkOwnership", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifest", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.FileManifest", null)
                        .WithMany("FileManifests")
                        .HasForeignKey("FileManifestId");

                    b.HasOne("Cotton.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifestChunk", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.Chunk", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkSha256")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Server.Database.Models.FileManifest", "FileManifest")
                        .WithMany()
                        .HasForeignKey("FileManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("FileManifest");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.Layout", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.Node", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.Layout", "Layout")
                        .WithMany("Nodes")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Server.Database.Models.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Layout");

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.NodeFile", b =>
                {
                    b.HasOne("Cotton.Server.Database.Models.FileManifest", "FileManifest")
                        .WithMany()
                        .HasForeignKey("FileManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Server.Database.Models.Node", "Node")
                        .WithMany("LayoutNodeFiles")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileManifest");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.FileManifest", b =>
                {
                    b.Navigation("FileManifests");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.Layout", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Cotton.Server.Database.Models.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("LayoutNodeFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
