// <auto-generated />
using System;
using Cotton.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cotton.Database.Migrations
{
    [DbContext(typeof(CottonDbContext))]
    [Migration("20260107231729_AddPreviewImageHashes")]
    partial class AddPreviewImageHashes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cotton.Database.Models.Benchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan>("Elapsed")
                        .HasColumnType("interval")
                        .HasColumnName("elapsed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("benchmarks");
                });

            modelBuilder.Entity("Cotton.Database.Models.Chunk", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<int>("CompressionAlgorithm")
                        .HasColumnType("integer")
                        .HasColumnName("compression_algorithm");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Hash");

                    b.ToTable("chunks");
                });

            modelBuilder.Entity("Cotton.Database.Models.ChunkOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ChunkHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chunk_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChunkHash");

                    b.HasIndex("OwnerId", "ChunkHash")
                        .IsUnique();

                    b.ToTable("chunk_ownerships");
                });

            modelBuilder.Entity("Cotton.Database.Models.CottonServerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowCrossUserDeduplication")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_cross_user_deduplication");

                    b.Property<bool>("AllowGlobalIndexing")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_global_indexing");

                    b.Property<int>("CipherChunkSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("cipher_chunk_size_bytes");

                    b.Property<int>("ComputionMode")
                        .HasColumnType("integer")
                        .HasColumnName("compution_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmailMode")
                        .HasColumnType("integer")
                        .HasColumnName("email_mode");

                    b.Property<int>("EncryptionThreads")
                        .HasColumnType("integer")
                        .HasColumnName("encryption_threads");

                    b.Property<int>("ImportSource")
                        .HasColumnType("integer")
                        .HasColumnName("import_source");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<int>("MaxChunkSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("max_chunk_size_bytes");

                    b.Property<string>("S3AccessKeyId")
                        .HasColumnType("text")
                        .HasColumnName("s3_access_key_id");

                    b.Property<string>("S3BucketName")
                        .HasColumnType("text")
                        .HasColumnName("s3_bucket_name");

                    b.Property<string>("S3EndpointUrl")
                        .HasColumnType("text")
                        .HasColumnName("s3_endpoint_url");

                    b.Property<string>("S3Region")
                        .HasColumnType("text")
                        .HasColumnName("s3_region");

                    b.Property<string>("S3SecretAccessKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("s3_secret_access_key_encrypted");

                    b.PrimitiveCollection<int[]>("ServerUsage")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("server_usage");

                    b.Property<int>("SessionTimeoutHours")
                        .HasColumnType("integer")
                        .HasColumnName("session_timeout_hours");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("smtp_password_encrypted");

                    b.Property<string>("SmtpSenderEmail")
                        .HasColumnType("text")
                        .HasColumnName("smtp_sender_email");

                    b.Property<string>("SmtpServerAddress")
                        .HasColumnType("text")
                        .HasColumnName("smtp_server_address");

                    b.Property<int?>("SmtpServerPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_server_port");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("boolean")
                        .HasColumnName("smtp_use_ssl");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("text")
                        .HasColumnName("smtp_username");

                    b.Property<int>("StorageSpaceMode")
                        .HasColumnType("integer")
                        .HasColumnName("storage_space_mode");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasColumnName("storage_type");

                    b.Property<bool>("TelemetryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("telemetry_enabled");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebdavHost")
                        .HasColumnType("text")
                        .HasColumnName("webdav_host");

                    b.Property<string>("WebdavPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("webdav_password_encrypted");

                    b.Property<string>("WebdavUsername")
                        .HasColumnType("text")
                        .HasColumnName("webdav_username");

                    b.HasKey("Id");

                    b.ToTable("server_settings");
                });

            modelBuilder.Entity("Cotton.Database.Models.DownloadToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FileManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_manifest_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FileManifestId");

                    b.ToTable("download_tokens");
                });

            modelBuilder.Entity("Cotton.Database.Models.FileManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ComputedContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("computed_content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("PreviewImageHash")
                        .HasColumnType("bytea")
                        .HasColumnName("preview_image_hash");

                    b.Property<byte[]>("ProposedContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("proposed_content_hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ComputedContentHash")
                        .IsUnique();

                    b.HasIndex("ProposedContentHash")
                        .IsUnique();

                    b.ToTable("file_manifests");
                });

            modelBuilder.Entity("Cotton.Database.Models.FileManifestChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ChunkHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chunk_hash");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_order");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_manifest_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChunkHash");

                    b.HasIndex("FileManifestId", "ChunkOrder")
                        .IsUnique();

                    b.ToTable("file_manifest_chunks");
                });

            modelBuilder.Entity("Cotton.Database.Models.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("layouts");
                });

            modelBuilder.Entity("Cotton.Database.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.HasIndex("LayoutId", "ParentId", "Type", "NameKey")
                        .IsUnique();

                    b.ToTable("nodes");
                });

            modelBuilder.Entity("Cotton.Database.Models.NodeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_manifest_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("OriginalNodeFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_node_file_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("FileManifestId", "NodeId");

                    b.HasIndex("NodeId", "NameKey")
                        .IsUnique();

                    b.ToTable("node_files");
                });

            modelBuilder.Entity("Cotton.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordPhc")
                        .HasColumnType("text")
                        .HasColumnName("password_phc");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("EasyExtensions.EntityFrameworkCore.Database.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Cotton.Database.Models.ChunkOwnership", b =>
                {
                    b.HasOne("Cotton.Database.Models.Chunk", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Database.Models.DownloadToken", b =>
                {
                    b.HasOne("Cotton.Database.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.FileManifest", "FileManifest")
                        .WithMany()
                        .HasForeignKey("FileManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FileManifest");
                });

            modelBuilder.Entity("Cotton.Database.Models.FileManifestChunk", b =>
                {
                    b.HasOne("Cotton.Database.Models.Chunk", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.FileManifest", "FileManifest")
                        .WithMany("FileManifestChunks")
                        .HasForeignKey("FileManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("FileManifest");
                });

            modelBuilder.Entity("Cotton.Database.Models.Layout", b =>
                {
                    b.HasOne("Cotton.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Database.Models.Node", b =>
                {
                    b.HasOne("Cotton.Database.Models.Layout", "Layout")
                        .WithMany("Nodes")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Layout");

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cotton.Database.Models.NodeFile", b =>
                {
                    b.HasOne("Cotton.Database.Models.FileManifest", "FileManifest")
                        .WithMany()
                        .HasForeignKey("FileManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.Node", "Node")
                        .WithMany("NodeFiles")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cotton.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileManifest");

                    b.Navigation("Node");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cotton.Database.Models.FileManifest", b =>
                {
                    b.Navigation("FileManifestChunks");
                });

            modelBuilder.Entity("Cotton.Database.Models.Layout", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Cotton.Database.Models.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("NodeFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
